### ISSUE TITLE
mismatch on quantlib vs quantlib-python in anaconda

### ISSUE THREAD

**Issue by novitk** [domosute/conda-quantlib#3]
JFYI

On https://anaconda.org/domosute both packages in the subject are listed as 1.17 version. It looks to me that quantlib is from 1.17 indeed, but python bindings are one version behind from 1.16 version.

**Comment by domosute** [comment]
Thanks for checking, I noticed build error, I will take a look sometimes later... For now, I removed the package from Anaconda cloud repo.

**Comment by domosute** [comment]
FYI, both packages are updated to 1.19.
